name: Build MT7981 U-Boot

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo apt update
          # 安装交叉编译器和必要工具
          sudo apt install -y gcc-aarch64-linux-gnu build-essential bc libssl-dev device-tree-compiler python3 python3-pip

      - name: Build U-Boot (Standard Layout)
        run: |
          # 编译 H3C NX30 Pro 的 SPI-NAND 版本
          # 默认通常是官方/标准分区布局
          ./build.sh mt7981-h3c-magic-nx30-pro spim-nand

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NX30P-U-Boot-Files
          path: output/*.bin
